# Generated by Django 4.2.3 on 2023-07-29 00:23

from django.db import migrations, models
import django.db.models.deletion
import site_setup.utils.model_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cor_hex', models.CharField(default='#000000', help_text='Preencher de forma hexadecimal #000000', max_length=7, verbose_name='Cor de fundo para esse status')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_filter', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plataforma | Status',
                'verbose_name_plural': 'Plataformas | Status',
                'ordering': ('order', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65, verbose_name='Nome da plataforma')),
                ('family_name', models.CharField(max_length=65, verbose_name='Nome da família')),
                ('logo', models.ImageField(blank=True, default='', upload_to='images/platforms/%Y/%m/', validators=[site_setup.utils.model_validators.validade_image])),
                ('description', models.TextField(blank=True, null=True)),
                ('name_link', models.CharField(default='Link do Daniel', max_length=25)),
                ('min_deposit', models.CharField(default='Deposito mínimo', max_length=50)),
                ('min_cash', models.CharField(default='Saque mínimo', max_length=50)),
                ('bonus', models.CharField(default='Bonus', max_length=50)),
                ('lucky_link', models.URLField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Plataforma ativa')),
                ('site_setup', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_setup.sitesetup')),
            ],
            options={
                'verbose_name': 'Plataforma | Cadastro',
                'verbose_name_plural': 'Plataformas | Cadastros',
                'ordering': ('order', '-updated_at'),
            },
        ),
    ]
