# Generated by Django 4.2.3 on 2023-07-29 00:38

from django.db import migrations, models
import site_setup.utils.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, default='', upload_to='images/icons/', validators=[site_setup.utils.model_validators.validade_image])),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plataforma | Icone da plataforma',
                'verbose_name_plural': 'Plataformas | Icones da plataforma',
            },
        ),
        migrations.CreateModel(
            name='SpecificDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plataforma | Detalhe especifico',
                'verbose_name_plural': 'Plataformas | Detalhes especificos',
            },
        ),
        migrations.AlterField(
            model_name='platform',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to='images/platforms/', validators=[site_setup.utils.model_validators.validade_image]),
        ),
    ]
