# Generated by Django 4.2.3 on 2023-07-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_icon_specificdetail_alter_platform_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='icons',
            field=models.ManyToManyField(blank=True, to='platforms.icon', verbose_name='Icones'),
        ),
        migrations.AddField(
            model_name='platform',
            name='specific_detail',
            field=models.ManyToManyField(blank=True, to='platforms.specificdetail', verbose_name='Detalhes especificos'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='lucky_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name_link',
            field=models.CharField(default='Link do Daniel', max_length=25, verbose_name='Nome descritivo do link'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Posição'),
        ),
    ]
