# Generated by Django 4.2.3 on 2023-07-29 01:08

from django.db import migrations, models
import django.db.models.deletion
import site_setup.utils.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0001_initial'),
        ('platforms', '0003_platform_icons_platform_specific_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='icon',
            field=models.ImageField(blank=True, default='', upload_to='images/icons/', validators=[site_setup.utils.model_validators.validade_image], verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Está ativo'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='min_cash',
            field=models.CharField(default='R$ 0', max_length=50),
        ),
        migrations.AlterField(
            model_name='platform',
            name='min_deposit',
            field=models.CharField(default='R$ 0', max_length=50),
        ),
        migrations.AlterField(
            model_name='platform',
            name='site_setup',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_setup.sitesetup', verbose_name='Site ativo'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='specificdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='specificdetail',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Está ativo'),
        ),
        migrations.AlterField(
            model_name='specificdetail',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='specificdetail',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='specificdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='statusplatform',
            name='cor_hex',
            field=models.CharField(default='#000000', help_text='Preencher de forma hexadecimal #000000', max_length=7, verbose_name='Cor de fundo'),
        ),
        migrations.AlterField(
            model_name='statusplatform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='statusplatform',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Está ativo'),
        ),
        migrations.AlterField(
            model_name='statusplatform',
            name='is_filter',
            field=models.BooleanField(default=True, verbose_name='Será filtrado'),
        ),
        migrations.AlterField(
            model_name='statusplatform',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='statusplatform',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='statusplatform',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
