# Generated by Django 4.2.3 on 2023-07-29 01:20

import autoslug.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0004_alter_icon_created_at_alter_icon_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now, editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
    ]
