# Generated by Django 4.2.3 on 2023-07-29 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0005_platform_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platforms.statusplatform'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='bonus',
            field=models.CharField(default='Bônus', max_length=50),
        ),
        migrations.AlterField(
            model_name='platform',
            name='lucky_link',
            field=models.URLField(blank=True, default='#', null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='min_cash',
            field=models.CharField(default='R$ 0', max_length=50, verbose_name='Saque mínimo'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='min_deposit',
            field=models.CharField(default='R$ 0', max_length=50, verbose_name='Depósito mínimo'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='specific_detail',
            field=models.ManyToManyField(blank=True, to='platforms.specificdetail', verbose_name='Detalhes específicos'),
        ),
    ]
