# Generated by Django 4.2.3 on 2023-07-29 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0006_platform_status_alter_platform_bonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platforms.statusplatform', verbose_name='Status'),
        ),
    ]
