# Generated by Django 4.2.4 on 2023-08-04 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0001_initial'),
        ('platforms', '0007_alter_platform_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='site_setup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_setup.sitesetup', verbose_name='Site ativo'),
        ),
    ]
