# Generated by Django 4.2.4 on 2023-08-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0008_alter_platform_site_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='is_filter',
            field=models.BooleanField(default=True, verbose_name='Será filtrado'),
        ),
    ]
