# Generated by Django 4.2.4 on 2023-08-05 16:56

from django.db import migrations, models
import site_setup.utils.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0009_icon_is_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusplatform',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/icons/', validators=[site_setup.utils.model_validators.validade_image], verbose_name='Icone'),
        ),
    ]
