# Generated by Django 4.2.4 on 2023-08-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0010_statusplatform_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='icons',
            field=models.ManyToManyField(blank=True, related_name='icons', to='platforms.statusplatform', verbose_name='Icones'),
        ),
    ]
