# Generated by Django 4.2.4 on 2023-08-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0011_alter_platform_icons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='bonus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='family_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da família'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='min_cash',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Saque mínimo'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='min_deposit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Depósito mínimo'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome da plataforma'),
        ),
    ]
