# Generated by Django 4.2.4 on 2023-08-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0012_alter_platform_bonus_alter_platform_family_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificdetail',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
    ]
