# Generated by Django 4.2.4 on 2023-08-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0013_alter_specificdetail_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='lucky_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
    ]
