# Generated by Django 4.2.4 on 2023-08-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0014_alter_platform_lucky_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Plataforma favorita'),
        ),
    ]
