# Generated by Django 4.2.4 on 2023-08-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0015_platform_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='is_old',
            field=models.BooleanField(default=False, verbose_name='Panela velha'),
        ),
    ]
