# Generated by Django 4.2.5 on 2023-09-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0016_platform_is_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Plataforma destaque'),
        ),
    ]
