# Generated by Django 4.2.6 on 2023-10-14 00:20

from django.db import migrations, models
import platforms.models.platform
import platforms.models.status
import site_setup.utils.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0018_alter_platform_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to=platforms.models.platform.unique_file_path, validators=[site_setup.utils.model_validators.validade_image]),
        ),
        migrations.AlterField(
            model_name='statusplatform',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=platforms.models.status.unique_file_path, validators=[site_setup.utils.model_validators.validade_image], verbose_name='Icone'),
        ),
    ]
