# Generated by Django 4.2.7 on 2023-12-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0019_alter_platform_logo_alter_statusplatform_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='is_payer',
            field=models.BooleanField(default=False, verbose_name='Favorita'),
        ),
    ]
