# Generated by Django 4.2.16 on 2025-02-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoS3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('arquivo', models.FileField(upload_to='uploads/')),
                ('chave_s3', models.CharField(blank=True, max_length=255)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('tipo_arquivo', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Arquivo S3',
                'verbose_name_plural': 'Arquivos S3',
            },
        ),
    ]
