# Generated by Django 4.2.16 on 2025-02-01 03:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_arquivos3'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivos3',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arquivos3',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='arquivos3',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
