# Generated by Django 4.2.23 on 2025-08-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_arquivos3_created_at_arquivos3_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arquivos3',
            options={'verbose_name': 'Upload de Arquivo', 'verbose_name_plural': 'Uploads de Arquivos'},
        ),
    ]
