# Generated by Django 4.2.16 on 2024-09-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='first_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Nome'),
        ),
    ]
