# Generated by Django 4.2.3 on 2023-07-26 14:07

from django.db import migrations, models
import site_setup.utils.model_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65)),
                ('description', models.CharField(max_length=255)),
                ('http_host', models.CharField(max_length=255)),
                ('favicon', models.ImageField(blank=True, default='', upload_to='assets/favicon/%Y/%m/', validators=[site_setup.utils.model_validators.validate_png])),
                ('background', models.ImageField(blank=True, default='', upload_to='assets/background/%Y/%m/', validators=[site_setup.utils.model_validators.validade_image])),
                ('login', models.BooleanField(default=True, verbose_name='Ativar Login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativar Site')),
            ],
            options={
                'verbose_name': 'Site Setup',
                'verbose_name_plural': 'Site Setup',
            },
        ),
    ]
