# Generated by Django 4.2.6 on 2023-10-11 02:33

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título do post')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('post', models.TextField(blank=True, null=True, verbose_name='Post')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Posição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Plataforma ativa')),
                ('site_setup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_setup.sitesetup', verbose_name='Site ativo')),
            ],
            options={
                'verbose_name': 'Blog | Cadastro',
                'verbose_name_plural': 'Blogs | Cadastros',
                'ordering': ('order', '-updated_at'),
            },
        ),
    ]
