# Generated by Django 4.2.6 on 2023-10-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtítulo do post'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Post ativo'),
        ),
    ]
