# Generated by Django 4.2.6 on 2023-10-11 03:39

from django.db import migrations, models
import site_setup.utils.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_posts_sub_title_alter_posts_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='thumbnail',
            field=models.ImageField(blank=True, default='', upload_to='images/thumbnail/', validators=[site_setup.utils.model_validators.validade_image]),
        ),
    ]
