# Generated by Django 4.2.3 on 2023-07-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cell_phone',
            field=models.CharField(max_length=50, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='E-mail'),
        ),
    ]
