# Generated by Django 4.2.4 on 2023-08-06 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('icon_fontawesome', models.CharField(max_length=255, verbose_name='Icone')),
                ('description', models.TextField(blank=True, help_text='Para separar entre parágrafos use ; ', null=True, verbose_name='Descrição')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Posição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='FAQ ativa')),
                ('site_setup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_setup.sitesetup', verbose_name='Site ativo')),
            ],
            options={
                'verbose_name': 'FAQ | Cadastro',
                'verbose_name_plural': 'FAQ | Cadastros',
                'ordering': ('order', '-updated_at'),
            },
        ),
    ]
