# Generated by Django 4.2.4 on 2023-08-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título')),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtítulo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Posição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='FAQ ativa')),
            ],
            options={
                'verbose_name': 'FAQ | Seção',
                'verbose_name_plural': 'FAQ | Seções',
                'ordering': ('order', '-updated_at'),
            },
        ),
    ]
