# Generated by Django 4.2.4 on 2023-08-23 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faq.section', verbose_name='Seção'),
        ),
    ]
