# Generated by Django 4.2.4 on 2023-08-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_faq_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='in_main_page',
            field=models.BooleanField(default=True, verbose_name='Na página principal'),
        ),
    ]
