# Generated by Django 4.2.4 on 2023-08-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_mobile', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contador de visita',
                'verbose_name_plural': 'Contador de visitas',
                'ordering': ('-updated_at',),
            },
        ),
    ]
