# Generated by Django 4.2.4 on 2023-08-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ('-created_at',), 'verbose_name': 'Contador de visita', 'verbose_name_plural': 'Contador de visitas'},
        ),
        migrations.RemoveField(
            model_name='visit',
            name='updated_at',
        ),
    ]
