# Generated by Django 4.2.4 on 2023-08-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counters', '0002_alter_visit_options_remove_visit_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_mobile', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contador de serviço',
                'verbose_name_plural': 'Contador de serviços',
                'ordering': ('-created_at',),
            },
        ),
    ]
