# Generated by Django 4.2.4 on 2023-08-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counters', '0003_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='ip_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='ip_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='IP'),
        ),
    ]
