# Generated by Django 4.2.4 on 2023-09-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counters', '0004_alter_services_ip_address_alter_visit_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='referer',
            field=models.CharField(default='direto', max_length=50, verbose_name='Referencia'),
        ),
    ]
