# Generated by Django 4.2.4 on 2023-09-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counters', '0005_visit_referer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='referer',
            field=models.CharField(default='http', max_length=50, verbose_name='Referencia'),
        ),
    ]
