# Generated by Django 4.2.5 on 2023-09-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counters', '0007_alter_visit_referer'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='is_iphone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='is_pwa',
            field=models.BooleanField(default=False),
        ),
    ]
