# Generated by Django 4.2.5 on 2023-09-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counters', '0008_visit_is_iphone_visit_is_pwa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='is_iphone',
            field=models.BooleanField(default=False, verbose_name='Iphone'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='is_mobile',
            field=models.BooleanField(default=False, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='is_pwa',
            field=models.BooleanField(default=False, verbose_name='PWA'),
        ),
    ]
