# Generated by Django 4.2.5 on 2023-09-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100, verbose_name='Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Notificação ativa')),
            ],
            options={
                'verbose_name': 'Notificação | Cadastro',
                'verbose_name_plural': 'Notificações | Cadastros',
                'ordering': ('-updated_at',),
            },
        ),
    ]
