# Generated by Django 4.2.5 on 2023-09-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='color',
            field=models.CharField(default='info', help_text='secondary, success, info, warning, danger, dark, light', max_length=20, verbose_name='Cor do aviso'),
        ),
    ]
