# Generated by Django 4.2.6 on 2023-10-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='color',
            field=models.CharField(choices=[('secondary', 'Azul'), ('success', 'Verde'), ('info', 'Azul Claro'), ('warning', 'Amarelo'), ('danger', 'Vermelho'), ('dark', 'Preto'), ('light', 'Branco')], max_length=20, verbose_name='Cor do aviso'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=255, verbose_name='Mensagem'),
        ),
    ]
