# Generated by Django 4.2.6 on 2023-10-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_color_alter_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='emoji',
            field=models.CharField(blank=True, choices=[('smile', '😊'), ('nice', '👍')], max_length=20, null=True, verbose_name='Emoji'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='color',
            field=models.CharField(choices=[('secondary', 'Azul'), ('success', 'Verde'), ('info', 'Azul Claro'), ('warning', 'Amarelo'), ('danger', 'Vermelho'), ('dark', 'Preto'), ('light', 'Branco')], default='info', max_length=20, verbose_name='Cor do aviso'),
        ),
    ]
