# Generated by Django 4.2.6 on 2023-10-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_emoji_alter_notification_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='emoji',
            field=models.CharField(blank=True, choices=[('smile', '😊'), ('nice', '👍'), ('checked', '✔'), ('info', '❕'), ('warning', '⚠'), ('danger', '🛑')], max_length=20, null=True, verbose_name='Emoji'),
        ),
    ]
