# Generated by Django 4.2.6 on 2023-10-26 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0001_initial'),
        ('notifications', '0006_notification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='site_setup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_setup.sitesetup', verbose_name='Site ativo'),
        ),
    ]
