# Generated by Django 4.2.7 on 2023-11-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notification_site_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date_to_send',
            field=models.DateField(blank=True, null=True, verbose_name='Data de envio'),
        ),
        migrations.AddField(
            model_name='notification',
            name='days_to_repeat',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quatidade de dias'),
        ),
        migrations.AddField(
            model_name='notification',
            name='time_to_send',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora do envio'),
        ),
    ]
