# Generated by Django 4.2.7 on 2023-11-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_notification_date_to_send_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='days_to_repeat',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Quatidade de dias'),
        ),
    ]
