INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    # 3d Apps
    "django_extensions",
    "widget_tweaks",
    "pwa",
    "rest_framework",
    "rest_framework.authtoken",
    "django_celery_beat",
    # "django_summernote",
    # LocalApp
    "ecr",
    "users",
    "core",
    "development",
    "fortune",
    "site_setup",
    "platforms",
    "videos",
    "faq",
    "counters",
    "notifications",
    "blog",
    "chat",
    "favorites",
    "iprof",
    "telegram_bot",
    "api",
]
