# Generated by Django 4.2.4 on 2023-08-05 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platforms', '0009_icon_is_filter'),
        ('site_setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('youtube', models.URLField(blank=True, null=True)),
                ('rumble', models.URLField(blank=True, null=True)),
                ('streaming', models.CharField(blank=True, choices=[('YT', 'YouTube'), ('RM', 'Rumble')], max_length=2, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Posição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Plataforma ativa')),
                ('icons', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platforms.icon', verbose_name='Icone')),
                ('site_setup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_setup.sitesetup', verbose_name='Site ativo')),
            ],
            options={
                'verbose_name': 'Video | Cadastro',
                'verbose_name_plural': 'Videos | Cadastros',
                'ordering': ('order', '-updated_at'),
            },
        ),
    ]
