# Generated by Django 4.2.4 on 2023-08-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Video ativo'),
        ),
    ]
