# Generated by Django 4.2.4 on 2023-08-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='youtube',
            field=models.URLField(blank=True, default='https://www.youtube.com/embed/', null=True),
        ),
    ]
