# Generated by Django 4.2.4 on 2023-08-05 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0013_alter_specificdetail_title'),
        ('videos', '0003_alter_video_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='icons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platforms.statusplatform', verbose_name='Icone'),
        ),
    ]
