# Generated by Django 4.2.4 on 2023-08-14 13:51

from django.db import migrations, models
import site_setup.utils.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_alter_video_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/platforms/', validators=[site_setup.utils.model_validators.validade_image], verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='video',
            name='streaming',
            field=models.CharField(blank=True, choices=[('YT', 'YouTube'), ('RM', 'Rumble'), ('EX', 'Externo')], max_length=2, null=True),
        ),
    ]
