# Generated by Django 4.2.4 on 2023-08-20 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_video_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='rumble',
        ),
        migrations.RemoveField(
            model_name='video',
            name='youtube',
        ),
    ]
