# Generated by Django 4.2.7 on 2023-11-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('completion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Treinamento ativo')),
            ],
            options={
                'verbose_name': 'Treinamento | Cadastro',
                'verbose_name_plural': 'Treinamentos | Cadastros',
                'ordering': ('-updated_at',),
            },
        ),
    ]
