# Generated by Django 4.2.7 on 2023-11-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='completion',
            field=models.TextField(verbose_name='Resposta'),
        ),
        migrations.AlterField(
            model_name='training',
            name='prompt',
            field=models.TextField(verbose_name='Pergunta'),
        ),
    ]
